### ISSUE TITLE
Code clean-up

### ISSUE THREAD

**Issue by hannahgooding** [fac19/prepare-me#72]
Quick question: Is there meant to be something before the comma [here](https://github.com/fac19/prepare-me/blob/911b2ef481eae0c76b8425e8e1aaf5bccc3cd75c/src/pages/StoryTemplates.js#L37)?

**Comment by Roger-Heathcote** [comment]
@Hannah That's intentional, if you want to get an element by destructuring an array but you don't need the preceding parameters you can omit them and just put the commas in. In this case we needed the second param. If we'd left the first one in our linter would have complained about unused variables and caused Travis to fail the build.
